# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TgsCli < Formula
  desc "Fast CLI client for searching Telegram"
  homepage "https://github.com/garenal1v3/tgs-cli"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v1.0.0/tgs-cli_darwin_amd64.tar.gz"
      sha256 "234a4baf1d119ed84eeecfb7f84890142c9b5da5346707e13edc814ea14424b3"

      define_method(:install) do
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v1.0.0/tgs-cli_darwin_arm64.tar.gz"
      sha256 "bfc02261aff5484d96e2be2f423a5e6d99c69de9604753c400c80cab66916ff0"

      define_method(:install) do
        bin.install "tgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v1.0.0/tgs-cli_linux_amd64.tar.gz"
      sha256 "1d1a9bd4ae33f9fcd92bc67dac08885389d88e49c4ac083a7203baf22f0889ca"
      define_method(:install) do
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v1.0.0/tgs-cli_linux_arm64.tar.gz"
      sha256 "97e63598265cb44951b928ecf256d1713ef729ce4c25ddab39555406eb092c46"
      define_method(:install) do
        bin.install "tgs"
      end
    end
  end
end
