# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TgsCli < Formula
  desc "Fast CLI client for searching Telegram"
  homepage "https://github.com/garenal1v3/tgs-cli"
  version "0.0.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v0.0.1/tgs-cli_darwin_amd64.tar.gz"
      sha256 "e4eafb2a1d4b3a7b27b0ac8a9dd00693964bb0c62e9a53551c6307243339273f"

      define_method(:install) do
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v0.0.1/tgs-cli_darwin_arm64.tar.gz"
      sha256 "be39aa4d0ca719dd170f7419dd4364cecd1cebd5d273327c55c287b3a3a1db65"

      define_method(:install) do
        bin.install "tgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v0.0.1/tgs-cli_linux_amd64.tar.gz"
      sha256 "941d14be94cb3c14f82852cf69b978ed21535ced9736a3d55b465b8812f13da9"
      define_method(:install) do
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garenal1v3/tgs-cli/releases/download/v0.0.1/tgs-cli_linux_arm64.tar.gz"
      sha256 "2ba0aa2bcd7fe5a851f951751d20d7e2e14b9662079cdff7f2acc40620f39caf"
      define_method(:install) do
        bin.install "tgs"
      end
    end
  end
end
